Implements running from parent directory #298
go-task/task pull request #408
Opened 2020-11-22 19:25 UTC by enc

Uses the absolute path to make sure we can move up.

It's not smart yet, but it works.

Also addresses #395 since it was so simple to change.

2020-11-22 21:20 UTC, enc commented
Ok, this will not work on windows...

I will check this later.

2022-01-27 22:59 UTC, amoutiers commented
Great feature !
Like git, docker-compose, ...

2022-03-24 16:21 UTC, mvgijssel commented
Yeah big +1 on this change!

2022-04-17 20:33 UTC, ghostsquad requested changes
This behavior can actually be _quite_ dangerous. I would recommend against implementation of this without further discussion of risk. Additionally, this change is not backwards compatible, right now an "error" is produced if you run task from a directory that does not contain a taskfile. As such, this feature should be hidden behind a feature flag in the CLI (with a default `enabled: false`).

Git CVE-2022-24765 describes the risk actually quite well:

https://github.blog/2022-04-12-git-security-vulnerability-announced/

2022-04-17 20:33 UTC, ghostsquad commented on docs/installation.md
> +go get -u github.com/go-task/task/cmd/task
you can no longer install task with `go get` as of 1.18.

https://tip.golang.org/doc/go1.18#introduction

This document should reflect the use of `go install`

2022-04-17 20:33 UTC, ghostsquad commented on taskfile/read/taskfile.go
> +			found = true
technically, you don't even need `found` here, you can just `break`.

2022-11-12 14:25 UTC, andreynering commented
Closing in favor of #920

2022-11-12 14:25 UTC, closed without merging